services:
  mastermind:
    image: ${IMAGE_NAME:-bob-nexus:latest}
    container_name: ${ENTITY_CONTAINER_NAME:-mastermind_core}
    # network_mode: host
    working_dir: /root
    # Standardized environment loading from localized .env (Swarm 8.0)
    env_file:
      - .env
    volumes:
      # REGISTRY: Access to materialized blueprints and configs (Read-Write for Mailbox)
      - nexus_entities:/app/entities:rw
      # PERSISTENCE: Isolated Named Volume for the entity state
      - root_data:/root:rw
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - alpha
    environment:
      - HOME=/root
      - ROS_HOME=/root/.ros
      - PYTHONPATH=/app/master/core
      - REDIS_HOST=${REDIS_HOST:-bob_nexus_redis}
      - NAME=${NAME}
      - ENTITY_CATEGORY=${ENTITY_CATEGORY}
      - WORKSPACE_POLICY=${WORKSPACE_POLICY}
      - ENABLE_ONBOARDING=${ENABLE_ONBOARDING:-true}
    # Use the framework entrypoint baked into the image
    command: "${ENTITY_ENTRYPOINT:-/app/master/core/entrypoint.sh}"
    restart: unless-stopped

networks:
  alpha:
    external: true

volumes:
  root_data:
    # Entities use unique named volumes for total isolation
    name: ${VOLUME_NAME:-nexus_entity_root}
  nexus_entities:
    # Shared Registry for configurations
    external: true
