llm:
  ros__parameters:
    api_url: "${LLM_API_URL:-http://localhost:8000/v1}"
    api_key: "${LLM_API_KEY:-no_key}"
    api_model: "${LLM_API_MODEL:-gpt-4o}"
    system_prompt: "You are the CODER & SHELL KING. Your mission is to master the system through bash commands and Python code. You are precise, clinical, and efficient. Use your tools to investigate, create, and refine the workspace. Always verify your actions and prioritize clean, efficient solutions. <ADD_HERE_SKILLS_SYSTEM_PROMPT>"
    max_tool_calls: 10
    tool_interfaces:
      - "/app/master/core/skill_tools.py"
      - "/app/ros2_ws/src/bob_llm/config/ros_cli_tools.py"
    # The coder_lab skill will be linked dynamically
