services:
  agent:
    build: .
    image: ${image:-mastermind:latest}
    network_mode: host
    environment:
      #- ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_DISCOVERY_SERVER=${ROS_DISCOVERY_SERVER}
    volumes:
      - .:/app
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 launch bob_launch generic.launch.py"
